query GetModularFeed($searchParams: [SearchParam], $debug: Boolean = false) {
  modularFeed(params: $searchParams, debug: $debug) {
    analyticsData {
      requestId
      searchPerformedEventUniqueId
      searchSessionId
      __typename
    }
    categoryInfo {
      categoryId
      isForcedCategory
      __typename
    }
    feedAdditions
    filters {
      ...modularFilterNumericRange
      ...modularFilterSelectionList
      __typename
    }
    legacyFeedOptions {
      ...legacyFeedOptionListSelection
      ...legacyFeedOptionNumericRange
      __typename
    }
    looseTiles {
      ...modularTileBanner
      ...modularTileBingAd
      ...modularTileGoogleDisplayAd
      ...modularTileJob
      ...modularTileEmptyState
      ...modularTileListing
      ...modularTileLocalDisplayAd
      ...modularTileSearchAlert
      ...modularTileSellerAd
      ...modularModuleTileAdsPostXAd
      __typename
    }
    modules {
      ...modularGridModule
      __typename
    }
    pageCursor
    query {
      ...modularQueryInfo
      __typename
    }
    requestTimeMetadata {
      resolverComputationTimeSeconds
      serviceRequestTimeSeconds
      totalResolverTimeSeconds
      __typename
    }
    searchAlert {
      alertId
      alertStatus
      searchAlertCount
      __typename
    }
    personalizationPath
    debugInformation @include(if: $debug) {
      rankedListings {
        listingId
        attributes {
          key
          value
          __typename
        }
        __typename
      }
      lastViewedItems {
        listingId
        attributes {
          key
          value
          __typename
        }
        __typename
      }
      categoryAffinities {
        affinity
        count
        decay
        affinityOwner
        __typename
      }
      rankingStats {
        key
        value
        __typename
      }
      __typename
    }
    __typename
  }
}

fragment modularFilterNumericRange on ModularFeedNumericRangeFilter {
  isExpandedHighlight
  lowerBound {
    ...modularFilterNumericRangeBound
    __typename
  }
  shortcutLabel
  shortcutRank
  subTitle
  targetName
  title
  type
  upperBound {
    ...modularFilterNumericRangeBound
    __typename
  }
  __typename
}

fragment modularFilterNumericRangeBound on ModularFeedNumericRangeFilterNumericRangeBound {
  label
  limit
  placeholderText
  targetName
  value
  __typename
}

fragment modularFilterSelectionList on ModularFeedSelectionListFilter {
  targetName
  title
  subTitle
  shortcutLabel
  shortcutRank
  type
  isExpandedHighlight
  options {
    ...modularFilterSelectionListOption
    __typename
  }
  __typename
}

fragment modularFilterSelectionListOption on ModularFeedSelectionListFilterOption {
  isDefault
  isSelected
  label
  subLabel
  value
  __typename
}

fragment legacyFeedOptionListSelection on FeedOptionListSelection {
  label
  labelShort
  name
  options {
    default
    label
    labelShort
    selected
    subLabel
    value
    __typename
  }
  position
  queryParam
  type
  __typename
}

fragment legacyFeedOptionNumericRange on FeedOptionNumericRange {
  label
  labelShort
  leftQueryParam
  lowerBound
  name
  options {
    currentValue
    label
    textHint
    __typename
  }
  position
  rightQueryParam
  type
  units
  upperBound
  __typename
}

fragment modularTileBanner on ModularFeedTileBanner {
  tileId
  tileType
  title
  __typename
}

fragment modularTileBingAd on ModularFeedTileBingAd {
  tileId
  bingAd {
    ouAdId
    adExperimentId
    adNetwork
    adRequestId
    adTileType
    adSettings {
      repeatClickRefractoryPeriodMillis
      collapsible
      __typename
    }
    bingClientId
    clickFeedbackUrl
    clickReturnUrl
    contentUrl
    deepLinkEnabled
    experimentDataHash
    image {
      height
      url
      width
      __typename
    }
    impressionFeedbackUrl
    impressionUrls
    viewableImpressionUrls
    installmentInfo {
      amount
      description
      downPayment
      __typename
    }
    itemName
    lowPrice
    price
    searchId
    sellerName
    templateFields {
      key
      value
      __typename
    }
    __typename
  }
  tileType
  __typename
}

fragment modularTileGoogleDisplayAd on ModularFeedTileGoogleDisplayAd {
  tileId
  googleDisplayAd {
    ouAdId
    additionalSizes
    adExperimentId
    adHeight
    adNetwork
    adPage
    adRequestId
    adTileType
    adWidth
    adaptive
    channel
    clickFeedbackUrl
    clientId
    contentUrl
    customTargeting {
      key
      values
      __typename
    }
    displayAdType
    errorDrawable {
      actionPath
      listImage {
        height
        url
        urlDark
        width
        __typename
      }
      __typename
    }
    experimentDataHash
    formatIds
    impressionFeedbackUrl
    personalizationProperties {
      key
      values
      __typename
    }
    prebidConfigs {
      key
      values {
        timeout
        tamSlotUUID
        liftoffPlacementIDs
        nimbusPriceMapping
        adPosition
        __typename
      }
      __typename
    }
    renderLocation
    searchId
    searchQuery
    templateId
    __typename
  }
  tileType
  __typename
}

fragment modularTileJob on ModularFeedTileJob {
  tileId
  tileType
  job {
    address {
      city
      state
      zipcode
      __typename
    }
    companyName
    datePosted
    image {
      height
      url
      width
      __typename
    }
    industry
    jobId
    jobListingUrl
    jobOwnerId
    pills {
      text
      type
      __typename
    }
    title
    apply {
      method
      value
      __typename
    }
    wageDisplayValue
    provider
    __typename
  }
  __typename
}

fragment modularTileEmptyState on ModularFeedTileEmptyState {
  tileId
  tileType
  title
  description
  iconType
  __typename
}

fragment modularTileListing on ModularFeedTileListing {
  tileId
  listing {
    ...modularListing
    __typename
  }
  tileType
  __typename
}

fragment modularListing on ModularFeedListing {
  listingId
  conditionText
  flags
  image {
    height
    url
    width
    __typename
  }
  video {
    url
    thumbnailUrl
    width
    height
    __typename
  }
  isFirmPrice
  locationName
  price
  title
  vehicleMiles
  __typename
}

fragment modularTileLocalDisplayAd on ModularFeedTileLocalDisplayAd {
  tileId
  localDisplayAd {
    ouAdId
    adExperimentId
    adNetwork
    adRequestId
    adTileType
    advertiserId
    businessName
    callToAction
    callToActionType
    clickFeedbackUrl
    contentUrl
    experimentDataHash
    headline
    image {
      height
      url
      width
      __typename
    }
    impressionFeedbackUrl
    searchId
    __typename
  }
  tileType
  __typename
}

fragment modularTileSearchAlert on ModularFeedTileSearchAlert {
  tileId
  tileType
  title
  __typename
}

fragment modularTileSellerAd on ModularFeedTileSellerAd {
  tileId
  listing {
    ...modularListing
    __typename
  }
  sellerAd {
    ouAdId
    adId
    adExperimentId
    adNetwork
    adRequestId
    adTileType
    clickFeedbackUrl
    experimentDataHash
    impressionFeedbackUrl
    searchId
    __typename
  }
  tileType
  __typename
}

fragment modularModuleTileAdsPostXAd on ModularFeedTileAdsPostXAd {
  ...modularTileAdsPostXAd
  moduleId
  moduleRank
  moduleType
  __typename
}

fragment modularTileAdsPostXAd on ModularFeedTileAdsPostXAd {
  tileId
  adsPostXAd {
    ouAdId
    adExperimentId
    adNetwork
    adRequestId
    adTileType
    clickFeedbackUrl
    experimentDataHash
    impressionFeedbackUrl
    searchId
    offer {
      beacons {
        noThanksClick
        close
        __typename
      }
      title
      description
      clickUrl
      image
      pixel
      ctaYes
      ctaNo
      perkswallLabel
      perkswallUrl
      __typename
    }
    __typename
  }
  tileType
  __typename
}

fragment modularGridModule on ModularFeedModuleGrid {
  moduleId
  collection
  formFactor
  grid {
    actionPath
    tiles {
      ...modularModuleTileBingAd
      ...modularModuleTileGoogleDisplayAd
      ...modularModuleTileListing
      ...modularModuleTileLocalDisplayAd
      ...modularModuleTileSellerAd
      __typename
    }
    __typename
  }
  moduleType
  rank
  rowIndex
  searchId
  subTitle
  title
  infoActionPath
  feedIndex
  __typename
}

fragment modularModuleTileBingAd on ModularFeedTileBingAd {
  ...modularTileBingAd
  moduleId
  moduleRank
  moduleType
  __typename
}

fragment modularModuleTileGoogleDisplayAd on ModularFeedTileGoogleDisplayAd {
  ...modularTileGoogleDisplayAd
  moduleId
  moduleRank
  moduleType
  __typename
}

fragment modularModuleTileListing on ModularFeedTileListing {
  ...modularTileListing
  moduleId
  moduleRank
  moduleType
  __typename
}

fragment modularModuleTileLocalDisplayAd on ModularFeedTileLocalDisplayAd {
  ...modularTileLocalDisplayAd
  moduleId
  moduleRank
  moduleType
  __typename
}

fragment modularModuleTileSellerAd on ModularFeedTileSellerAd {
  ...modularTileSellerAd
  moduleId
  moduleRank
  moduleType
  __typename
}

fragment modularQueryInfo on ModularFeedQueryInfo {
  appliedQuery
  decisionType
  originalQuery
  suggestedQuery
  __typename
}
